### ISSUE TITLE
Visualize needle plans

### ISSUE THREAD

**Issue by ungi** [jbt2887/CISC472#6]
Name fiducials as E1, T1, E2, T2, etc. for needle entry points and needle target points. E1 can have multiple T1s.
Write a function that puts cylinders between E and T points.
The cylinder should be vtkMRMLModelNode with slice intersections.
Here is an example how to create a model node. (The example has other stuff in it.)

# Create model from multiple sources and use different colors

view = slicer.app.layoutManager().threeDWidget(0).threeDView()
renderWindow = view.renderWindow()
renderers = renderWindow.GetRenderers()
firstRenderer = renderers.GetFirstRenderer()
firstRenderer.SetUseDepthPeeling(True)

append = vtk.vtkAppendPolyData()

source = vtk.vtkCylinderSource()
source.SetRadius( 10 )
source.SetHeight( 30 )
source.Update()
cylinder1 = source.GetOutput()
colors1 = vtk.vtkIntArray()
colors1.SetNumberOfValues(cylinder1.GetNumberOfPoints())
for i in range(cylinder1.GetNumberOfPoints()):
  colors1.SetValue(i, 1)

cylinder1.GetPointData().SetScalars(colors1)

append.AddInputData( source.GetOutput() )

source2 = vtk.vtkCylinderSource()
source2.SetRadius( 15 )
source2.SetHeight( 10 )
source2.Update()
cylinder2 = source2.GetOutput()
colors2 = vtk.vtkIntArray()
colors2.SetNumberOfValues(cylinder2.GetNumberOfPoints())
for i in range(cylinder2.GetNumberOfPoints()):
  colors2.SetValue(i, 2)

cylinder2.GetPointData().SetScalars(colors2)

append.AddInputData( source2.GetOutput() )
append.Update()

model = slicer.vtkMRMLModelNode()
slicer.mrmlScene.AddNode( model )
model.SetName( "CModel" )
model.SetAndObservePolyData( append.GetOutput() )
display = slicer.vtkMRMLModelDisplayNode()
slicer.mrmlScene.AddNode( display )
colorTableNode = slicer.util.getFirstNodeByName('GenericColors')
display.SetAndObserveColorNodeID(colorTableNode.GetID())
display.SetScalarVisibility(True)
      
model.SetAndObserveDisplayNodeID( display.GetID() )

**Comment by jbt2887** [comment]
Code written for taking two points and creating a vtk tube filter.
Still need to visualize the results

**Comment by jbt2887** [comment]
Needle tips now correspond to fiducials
